componentsVersion: 40.0.0
projects:
  support-base:
    path: components/support/base
    description: 'Base component containing building blocks for components.'
    publish: true
  support-ktx:
    path: components/support/ktx
    description: 'A set of Kotlin extensions.'
    publish: true
  support-test:
    path: components/support/test
    description: 'A collection of helpers for testing components (local unit tests).'
    publish: true
  support-utils:
    path: components/support/utils
    description: 'A collection of generic helper classes.'
    publish: true
  lib-publicsuffixlist:
    path: components/lib/publicsuffixlist
    description: 'A library for reading and using the public suffix list.'
    publish: true
